using System.Globalization;

namespace MorseTrainer.Localization;

public enum AppLanguage
{
    System = 0,
    Russian = 1,
    English = 2
}

/// <summary>
/// Локализация интерфейса. Ключ — русская строка как она написана в XAML и коде,
/// значение — английский перевод. Нет перевода — показывается русский текст.
/// </summary>
public static class Texts
{
    public static AppLanguage Language { get; private set; } = AppLanguage.Russian;

    public static bool IsEnglish { get; private set; }

    /// <summary>Выбор языка: системный (английский для всех, кроме русской локали), русский или английский.</summary>
    public static void Apply(AppLanguage language, string? systemTwoLetterIso = null)
    {
        Language = language;
        IsEnglish = language switch
        {
            AppLanguage.English => true,
            AppLanguage.Russian => false,
            _ => systemTwoLetterIso is not null && !systemTwoLetterIso.Equals("ru", StringComparison.OrdinalIgnoreCase)
        };
    }

    public static string T(string russian)
    {
        return IsEnglish && English.TryGetValue(russian, out var translated) ? translated : russian;
    }

    public static string F(string russian, params object?[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, T(russian), args);
    }

    public static IReadOnlyDictionary<string, string> Translations => English;

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // ---- общее, шапка, язык ----
        ["Тренировка и изучение азбуки Морзе"] = "Morse code training and learning",
        ["Тема: системная"] = "Theme: system",
        ["Тема: тёмная"] = "Theme: dark",
        ["Тема: светлая"] = "Theme: light",
        ["Язык: системный"] = "Language: system",
        ["Язык: русский"] = "Language: Russian",
        ["Язык: English"] = "Language: English",
        ["Язык"] = "Language",
        ["Системный"] = "System",
        ["Русский (Russian)"] = "Russian",
        ["English"] = "English",
        ["Язык интерфейса изменится после перезапуска приложения."] = "The interface language will change after the app restarts.",
        ["Обновления"] = "Updates",
        ["Проверить, вышла ли новая версия на GitHub. Интернет нужен только для этой проверки."] = "Check GitHub for a new version. Internet is needed only for this check.",
        ["Проверяю…"] = "Checking…",
        ["Обновление Morse Trainer"] = "Morse Trainer update",
        ["Тренировка и изучение азбуки Морзе · версия {0}"] = "Morse code training and learning · version {0}",
        ["Доступна версия {0}, у вас {1}.{2}\n\nОткрыть страницу загрузки?"] = "Version {0} is available, you have {1}.{2}\n\nOpen the download page?",
        ["У вас последняя версия {0}."] = "You have the latest version {0}.",
        ["Не удалось проверить обновления. Проверьте подключение к интернету.\n\n{0}"] = "Could not check for updates. Check your internet connection.\n\n{0}",
        ["F5 — воспроизведение    Esc — остановка    Все данные хранятся только на этом компьютере"] = "F5 — play    Esc — stop    All data stays on this computer",
        // ---- тренировка (Windows) ----
        ["Тренировка"] = "Training",
        ["Параметры задания"] = "Task settings",
        ["Профиль настроек"] = "Settings profile",
        ["Сохранить профиль"] = "Save profile",
        ["Удалить"] = "Delete",
        ["Экспорт…"] = "Export…",
        ["Сохранить все профили в файл, чтобы перенести на другой компьютер или телефон"] = "Save all profiles to a file to move them to another computer or phone",
        ["Импорт…"] = "Import…",
        ["Загрузить профили из файла; одноимённые профили будут заменены"] = "Load profiles from a file; profiles with the same name will be replaced",
        ["Алфавит"] = "Alphabet",
        ["Русский"] = "Russian",
        ["Латинский"] = "Latin",
        ["Русский и латинский"] = "Russian and Latin",
        ["Состав задания"] = "Task content",
        ["Только буквы"] = "Letters only",
        ["Только цифры"] = "Digits only",
        ["Буквы и цифры"] = "Letters and digits",
        ["Буквы, цифры и знаки"] = "Letters, digits and punctuation",
        ["Все символы"] = "All symbols",
        ["Выбранные символы"] = "Selected symbols",
        ["Метод Коха: по уровням"] = "Koch method: by levels",
        ["Метод Коха"] = "Koch method",
        ["Собственный набор"] = "Custom set",
        ["Ничего не выбрано"] = "Nothing selected",
        ["Выбрать символы"] = "Choose symbols",
        ["Уровень 2"] = "Level 2",
        ["Новый символ добавляйте, когда точность держится на 90% и выше. Последний добавленный звучит чаще остальных."] = "Add a new symbol when accuracy stays at 90% or higher. The latest symbol is played more often.",
        ["Количество групп"] = "Number of groups",
        ["В каждой группе 5 символов"] = "Each group has 5 symbols",
        ["Скорость знака"] = "Character speed",
        ["60 знаков/мин"] = "60 cpm",
        ["Тональность"] = "Tone",
        ["700 Гц"] = "700 Hz",
        ["Громкость"] = "Volume",
        ["Пауза между символами"] = "Gap between symbols",
        ["3 точки"] = "3 dots",
        ["Пауза между группами"] = "Gap between groups",
        ["7 точек"] = "7 dots",
        ["Пресет Фарнсворта"] = "Farnsworth preset",
        ["Пресет Фарнсворта применён"] = "Farnsworth preset applied",
        ["Символы не медленнее 90 знаков/мин, паузы 9 точек между символами и 21 между группами: ухо запоминает ритм знака, а не считает точки."] = "Characters at 90 cpm or faster, gaps of 9 dots between symbols and 21 between groups: the ear learns the rhythm of a character instead of counting dots.",
        ["Символы не медленнее 90 знаков/мин, паузы 9 и 21 точка: ухо запоминает ритм знака, а не считает точки."] = "Characters at 90 cpm or faster, gaps of 9 and 21 dots: the ear learns the rhythm of a character instead of counting dots.",
        ["Чаще повторять символы с ошибками"] = "Repeat mistaken symbols more often",
        ["Символы, в которых вы ошибались (по истории тренировок), попадают в задание втрое чаще."] = "Symbols you got wrong (from training history) appear three times as often.",
        ["Перед заданием проигрывать Ж Ж Ж"] = "Play Ж Ж Ж before the task",
        ["Сигнал Ж Ж Ж перед заданием"] = "Ж Ж Ж signal before the task",
        ["Пауза после Ж Ж Ж"] = "Pause after Ж Ж Ж",
        ["21 точка"] = "21 dots",
        ["Сгенерировать задание"] = "Generate task",
        ["Ctrl+G — создать новое задание"] = "Ctrl+G — new task",
        ["Подготавливаем задание…"] = "Preparing the task…",
        ["Подготовка звука…"] = "Preparing audio…",
        ["ГЕНЕРАЦИЯ"] = "GENERATING",
        ["Формируем случайные группы и звук…"] = "Building random groups and audio…",
        ["НЕ ГОТОВО"] = "NOT READY",
        ["ГОТОВО"] = "READY",
        ["ОШИБКА"] = "ERROR",
        ["Правильный ответ"] = "Correct answer",
        ["Показать"] = "Show",
        ["Скрыть"] = "Hide",
        ["▶  Слушать"] = "▶  Play",
        ["■  Стоп"] = "■  Stop",
        ["↻  Повторить"] = "↻  Repeat",
        ["Ожидание задания"] = "Waiting for a task",
        ["Готово к воспроизведению · {0}"] = "Ready to play · {0}",
        ["Идёт воспроизведение…"] = "Playing…",
        ["СЛУШАЕМ"] = "LISTENING",
        ["Прослушивание завершено — введите ответ"] = "Playback finished — type your answer",
        ["ВАШ ОТВЕТ"] = "YOUR ANSWER",
        ["Введите то, что услышали"] = "Type what you heard",
        ["Проверить ответ"] = "Check answer",
        ["Пробелы между группами при проверке не учитываются"] = "Spaces between groups are ignored when checking",
        ["Отлично: все символы распознаны правильно"] = "Excellent: all symbols are correct",
        ["БЕЗ ОШИБОК"] = "NO MISTAKES",
        ["ЕСТЬ ОШИБКИ"] = "MISTAKES",
        ["Ошибки: {0}{1}"] = "Mistakes: {0}{1}",
        ["ТОЧНОСТЬ"] = "ACCURACY",
        ["ПОПЫТКИ"] = "ATTEMPTS",
        ["СЛОЖНЫЕ СИМВОЛЫ"] = "HARD SYMBOLS",
        ["Сохранить TXT"] = "Save TXT",
        ["Экспорт WAV"] = "Export WAV",
        ["Сохранить задание"] = "Save task",
        ["Текстовый файл (*.txt)|*.txt"] = "Text file (*.txt)|*.txt",
        ["Создано: {0:dd.MM.yyyy HH:mm}"] = "Created: {0:dd.MM.yyyy HH:mm}",
        ["Групп: {0} × 5"] = "Groups: {0} × 5",
        ["Скорость: {0} знаков/мин"] = "Speed: {0} cpm",
        ["Тональность: {0} Гц"] = "Tone: {0} Hz",
        ["Паузы: символы {0}, группы {1}"] = "Gaps: symbols {0}, groups {1}",
        ["Старт: Ж Ж Ж, затем пауза {0} точек"] = "Start: Ж Ж Ж, then a pause of {0} dots",
        ["Стартовый сигнал: выключен"] = "Start signal: off",
        ["Задание:"] = "Task:",
        ["Экспортировать звук"] = "Export audio",
        ["Звуковой файл WAV (*.wav)|*.wav"] = "WAV audio file (*.wav)|*.wav",
        ["Не удалось подготовить звук"] = "Could not prepare audio",
        ["Не удалось создать задание"] = "Could not create the task",
        ["Не удалось создать задание.\n\n{0}"] = "Could not create the task.\n\n{0}",
        ["Не удалось воспроизвести звук.\n\n{0}"] = "Could not play audio.\n\n{0}",
        ["В выбранном наборе нет символов. Откройте выбор и отметьте хотя бы одну букву или цифру."] = "The selected set has no symbols. Open the selection and check at least one letter or digit.",
        ["Количество групп должно быть целым числом от 1 до 100."] = "The number of groups must be a whole number from 1 to 100.",
        ["Проверьте параметры"] = "Check the settings",
        [" · старт Ж Ж Ж"] = " · start Ж Ж Ж",
        ["{0} групп × 5 · {1} знаков/мин · паузы {2}/{3}{4}"] = "{0} groups × 5 · {1} cpm · gaps {2}/{3}{4}",
        ["{0} символов: {1}"] = "{0} symbols: {1}",
        ["{0} знаков/мин"] = "{0} cpm",
        ["{0} зн/мин"] = "{0} cpm",
        ["{0} Гц"] = "{0} Hz",
        ["{0} точек"] = "{0} dots",
        ["{0} сек"] = "{0} s",
        ["ПРОФИЛЬ СОХРАНЁН"] = "PROFILE SAVED",
        ["Введите название профиля."] = "Enter a profile name.",
        ["Профили"] = "Profiles",
        ["Экспорт профилей"] = "Export profiles",
        ["Профили Morse Trainer (*.json)|*.json"] = "Morse Trainer profiles (*.json)|*.json",
        ["ПРОФИЛИ ЭКСПОРТИРОВАНЫ"] = "PROFILES EXPORTED",
        ["Импорт профилей"] = "Import profiles",
        ["Профили Morse Trainer (*.json)|*.json|Все файлы (*.*)|*.*"] = "Morse Trainer profiles (*.json)|*.json|All files (*.*)|*.*",
        ["Импортировано профилей: {0}."] = "Profiles imported: {0}.",
        ["Импортировано профилей: {0}"] = "Profiles imported: {0}",
        // ---- обучение ----
        ["Обучение"] = "Learning",
        ["Раздел"] = "Section",
        ["Русские буквы"] = "Russian letters",
        ["Латинские буквы"] = "Latin letters",
        ["Цифры"] = "Digits",
        ["Знаки"] = "Punctuation",
        ["Воспроизведение"] = "Playback",
        ["Напев на экране + сигнал"] = "Chant on screen + signal",
        ["Естественный офлайн-голос + сигнал"] = "Natural offline voice + signal",
        ["Поиск по букве или напеву"] = "Search by letter or chant",
        ["Сейчас изучаем"] = "Now learning",
        ["Выберите карточку"] = "Pick a card",
        ["Проверочное задание"] = "Quiz",
        ["Прослушайте сигнал и выберите символ"] = "Listen to the signal and pick the symbol",
        ["▶  Новое задание"] = "▶  New question",
        ["Нажмите «Новое задание»"] = "Press “New question”",
        ["Произносим напев…"] = "Speaking the chant…",
        ["Офлайн-напев недоступен — воспроизводим сигнал"] = "Offline chant unavailable — playing the signal",
        ["Слушаем ритм символа…"] = "Listening to the symbol rhythm…",
        ["Готово — можно прослушать ещё раз"] = "Done — you can listen again",
        ["Для проверки нужно не менее четырёх символов."] = "The quiz needs at least four symbols.",
        ["Слушайте…"] = "Listen…",
        ["Какой символ прозвучал?"] = "Which symbol was that?",
        ["Верно: {0} — {1}"] = "Correct: {0} — {1}",
        ["Правильно: {0} — {1}"] = "Correct: {0} — {1}",
        ["Правильный ответ: {0} — {1}"] = "Correct answer: {0} — {1}",
        ["Результат: {0} / {1}"] = "Score: {0} / {1}",
        ["Результат: 0 / 0"] = "Score: 0 / 0",
        ["Напевы сохранены в приложении и работают без интернета"] = "Chants are stored in the app and work offline",
        ["Найти"] = "Search",
        ["Голос"] = "Voice",
        ["Сигнал"] = "Signal",
        ["Проверка на слух"] = "Listening quiz",
        ["Новое"] = "New",
        ["Русские"] = "Russian",
        ["Латинские"] = "Latin",
        ["Русские и латинские"] = "Russian and Latin",
        ["Голос недоступен"] = "Voice unavailable",
        ["Для этого символа не найден встроенный напев."] = "No built-in chant for this symbol.",
        ["Не удалось воспроизвести"] = "Could not play",
        ["Закрыть"] = "Close",
        // ---- выбор символов ----
        ["Выбор символов"] = "Symbol selection",
        ["Выберите изученные символы"] = "Choose the symbols you know",
        ["Генератор будет использовать только отмеченные символы."] = "The generator will use only the checked symbols.",
        ["Выбрать раздел"] = "Select section",
        ["Выбрать всё"] = "Select all",
        ["Выбрать все"] = "Select all",
        ["Очистить"] = "Clear",
        ["Отмена"] = "Cancel",
        ["Применить"] = "Apply",
        ["Выберите хотя бы один символ."] = "Select at least one symbol.",
        ["Выбрано: {0}"] = "Selected: {0}",
        ["Выбрано: 0"] = "Selected: 0",
        // ---- передача ----
        ["Передача"] = "Sending",
        ["Передача ключом"] = "Sending with a key",
        ["Точка — короткое нажатие, тире — втрое длиннее. Пауза в 3 точки завершает символ, в 7 точек — группу. Скорость, алфавит и тон берутся из вкладки «Тренировка»."] = "A dot is a short press, a dash is three times longer. A 3-dot pause ends a symbol, a 7-dot pause ends a group. Speed, alphabet and tone come from the Training tab.",
        ["Точка — короткое нажатие, тире — втрое длиннее. Пауза в 3 точки завершает символ, в 7 точек — группу. Скорость, алфавит и тон берутся из настроек."] = "A dot is a short press, a dash is three times longer. A 3-dot pause ends a symbol, a 7-dot pause ends a group. Speed, alphabet and tone come from Settings.",
        ["Точка: 100 мс · тире от 200 мс"] = "Dot: 100 ms · dash from 200 ms",
        ["Точка: {0:0} мс · тире от {1:0} мс"] = "Dot: {0:0} ms · dash from {1:0} ms",
        ["Что передавать"] = "What to send",
        ["Свободная передача"] = "Free sending",
        ["Задание: группы по 5 символов"] = "Task: groups of 5 symbols",
        ["Новое задание"] = "New task",
        ["Проверить передачу"] = "Check sending",
        ["КЛЮЧ"] = "KEY",
        ["нажимайте мышью здесь или удерживайте ПРОБЕЛ"] = "click and hold here or hold SPACE",
        ["Стереть символ"] = "Erase symbol",
        ["Принято"] = "Received",
        ["Задание"] = "Task",
        ["Сгенерируйте группы, передайте их ключом и проверьте."] = "Generate groups, send them with the key and check.",
        ["В выбранном наборе нет символов: измените состав задания на вкладке «Тренировка»."] = "The selected set has no symbols: change the task content on the Training tab.",
        ["Передайте текст выше, затем нажмите «Проверить передачу»."] = "Send the text above, then press “Check sending”.",
        ["Отлично: передано без ошибок."] = "Excellent: sent without mistakes.",
        ["Точность {0:0.#}%. Ошибки: {1}{2}"] = "Accuracy {0:0.#}%. Mistakes: {1}{2}",
        ["Точность {0:0.#}%. Ошибки: {1}"] = "Accuracy {0:0.#}%. Mistakes: {1}",
        // ---- прогресс ----
        ["Прогресс"] = "Progress",
        ["История тренировок"] = "Training history",
        ["ТРЕНИРОВОК"] = "SESSIONS",
        ["СРЕДНЯЯ ТОЧНОСТЬ"] = "AVERAGE ACCURACY",
        ["ЛУЧШАЯ"] = "BEST",
        ["ПРИНЯТО СИМВОЛОВ"] = "SYMBOLS RECEIVED",
        ["Когда"] = "When",
        ["Профиль"] = "Profile",
        ["Скорость"] = "Speed",
        ["Групп"] = "Groups",
        ["Точность"] = "Accuracy",
        ["Ошибки"] = "Mistakes",
        ["По дням"] = "By day",
        ["Пока пусто"] = "Nothing yet",
        ["СЛОЖНЫЕ СИМВОЛЫ ЗА ВСЁ ВРЕМЯ"] = "HARD SYMBOLS OVERALL",
        ["Результат записывается при первой проверке ответа по каждому заданию. История хранится только на этом компьютере."] = "The result is recorded on the first check of each task. History is stored only on this computer.",
        ["Очистить историю"] = "Clear history",
        ["Удалить все записи о тренировках на этом компьютере?"] = "Delete all training records on this computer?",
        ["Удалить все записи о тренировках на этом устройстве?"] = "Delete all training records on this device?",
        ["Тренировок пока нет"] = "No sessions yet",
        ["Проверьте ответ в тренировке, и результат появится здесь."] = "Check an answer in Training and the result will appear here.",
        ["Последние тренировки"] = "Recent sessions",
        ["История хранится только на этом устройстве."] = "History is stored only on this device.",
        ["тренировка"] = "session",
        ["тренировки"] = "sessions",
        ["тренировок"] = "sessions",
        ["{0} {1} · средняя точность {2:0.#}%"] = "{0} {1} · average accuracy {2:0.#}%",
        ["Последние 10: {0:0.#}% · лучшая: {1:0.#}% · "] = "Last 10: {0:0.#}% · best: {1:0.#}% · ",
        ["принято {0} из {1} символов"] = "{0} of {1} symbols received",
        ["Ошибок в символах не было"] = "No symbol mistakes",
        ["Чаще всего ошибки: "] = "Most mistakes: ",
        ["За всё время: {0} · средняя точность {1:0.#}% · лучшая {2:0.#}%"] = "All time: {0} · average accuracy {1:0.#}% · best {2:0.#}%",
        // ---- телефон: тренировка ----
        ["Профиль: Основной"] = "Profile: Основной",
        ["Профиль: {0}"] = "Profile: {0}",
        ["Настроить"] = "Settings",
        ["Параметры"] = "Parameters",
        ["10 групп × 5 · 60 знаков/мин"] = "10 groups × 5 · 60 cpm",
        ["Перед началом: Ж Ж Ж → пауза → задание"] = "Before start: Ж Ж Ж → pause → task",
        ["Сгенерировать новое задание"] = "Generate a new task",
        ["▶ Слушать"] = "▶ Play",
        ["■ Стоп"] = "■ Stop",
        ["↻ Ещё раз"] = "↻ Again",
        ["Подготовьте задание"] = "Prepare a task",
        ["Создаём задание…"] = "Creating the task…",
        ["Готово · {0:mm\\:ss}"] = "Done · {0:mm\\:ss}",
        ["Сначала Ж Ж Ж, затем начнётся задание…"] = "First Ж Ж Ж, then the task starts…",
        ["Готово — введите ответ"] = "Done — type your answer",
        ["Воспроизведение остановлено"] = "Playback stopped",
        ["Введите услышанные группы"] = "Type the groups you heard",
        ["Например: АГЖДЕ БВГДА"] = "For example: АГЖДЕ БВГДА",
        ["Точность: —"] = "Accuracy: —",
        ["Точность: {0:0.#}%"] = "Accuracy: {0:0.#}%",
        ["Пробелы между группами не учитываются"] = "Spaces between groups are ignored",
        ["Нет символов"] = "No symbols",
        ["Откройте настройки и выберите хотя бы один символ."] = "Open Settings and select at least one symbol.",
        ["Понятно"] = "OK",
        ["Ошибка"] = "Error",
        [" · Ж Ж Ж + пауза {0}"] = " · Ж Ж Ж + pause {0}",
        [" · без сигнала старта"] = " · no start signal",
        [" · Кох: уровень {0}"] = " · Koch: level {0}",
        ["{0} групп × 5 · {1} знаков/мин · "] = "{0} groups × 5 · {1} cpm · ",
        ["{0} Гц · паузы {1}/{2}{3}"] = "{0} Hz · gaps {1}/{2}{3}",
        // ---- телефон: настройки ----
        ["Настройки"] = "Settings",
        ["Выберите профиль"] = "Select a profile",
        ["Название профиля"] = "Profile name",
        ["Сохранить"] = "Save",
        ["Поделиться"] = "Share",
        ["Вставить из буфера"] = "Paste from clipboard",
        ["«Поделиться» отправляет профили текстом (например, себе в мессенджер) и копирует его в буфер; «Вставить из буфера» принимает такой текст на другом устройстве. Одноимённые профили заменяются."] = "“Share” sends the profiles as text (for example, to yourself in a messenger) and copies it to the clipboard; “Paste from clipboard” accepts such text on another device. Profiles with the same name are replaced.",
        ["Профили скопированы в буфер и отправлены"] = "Profiles copied to the clipboard and shared",
        ["Не удалось поделиться"] = "Could not share",
        ["{0}\nСкопируйте текст профилей (из «Поделиться» на другом устройстве) и нажмите кнопку снова."] = "{0}\nCopy the profiles text (from “Share” on the other device) and press the button again.",
        ["Профиль «{0}» сохранён"] = "Profile “{0}” saved",
        ["Оформление"] = "Appearance",
        ["Тема"] = "Theme",
        ["Системная"] = "System",
        ["Тёмная"] = "Dark",
        ["Светлая"] = "Light",
        ["Режим"] = "Mode",
        ["Метод Коха: уровень 2"] = "Koch method: level 2",
        ["Метод Коха: уровень {0} из {1}"] = "Koch method: level {0} of {1}",
        ["Параметры тренировки"] = "Training settings",
        ["Сохранено {0:HH:mm}"] = "Saved {0:HH:mm}",
        ["Настройки сохраняются автоматически"] = "Settings are saved automatically",
        ["О программе"] = "About",
        ["Проверить обновления"] = "Check for updates",
        ["Интернет нужен только для этой проверки, всё остальное работает без сети."] = "Internet is needed only for this check; everything else works offline.",
        ["Есть обновление"] = "Update available",
        ["Доступна версия {0}, у вас {1}.{2}"] = "Version {0} is available, you have {1}.{2}",
        ["Скачать"] = "Download",
        ["Позже"] = "Later",
        ["Обновлений нет"] = "No updates",
        ["Не удалось проверить"] = "Could not check",
        ["Проверьте подключение к интернету.\n\n{0}"] = "Check your internet connection.\n\n{0}",
        ["Ошибки: "] = "Mistakes: ",
        ["Профили Morse Trainer"] = "Morse Trainer profiles",
        // ---- отчёт о сбое (телефон) ----
        ["Есть отчёт о сбое"] = "Crash report available",
        ["Отчёт о сбое от {0:dd.MM.yyyy HH:mm}"] = "Crash report from {0:dd.MM.yyyy HH:mm}",
        ["Приложение закрывалось само. Отправьте отчёт разработчику (например, себе в мессенджер и дальше на GitHub), затем удалите его."] = "The app closed by itself. Send the report to the developer (for example, to yourself in a messenger and then to GitHub), then delete it.",
        ["Отправить отчёт"] = "Send report",
        ["Удалить отчёт"] = "Delete report",
        ["Отчёт о сбое Morse Trainer"] = "Morse Trainer crash report",
        ["Отчёт о сбое удалён"] = "Crash report deleted",
        // заглушки карточки обучения до выбора символа: одинаковы на обоих языках
        ["А"] = "А",
        ["ай-даа"] = "ай-даа",
    };
}
